#:kivy 1.0

<ScrollableText>:
        
<PycalcCodeInput>:
    id: input
    size_hint_y: None
    multiline: False
    height: self.font_size * 1.5 + 10
    font_name: 'VeraMono'
    foreground_color: (1, 1, 1, 1)
    cursor_color: (0.8, 0.8, 0.8, 0.9)
    background_color: (0.2, 0.2, 0.2, 1) if self.focus else (0.1, 0.1, 0.1, 1)

<CodeOutput>:
    size_hint_y: None
    id: label
    padding: 5, 5
    font_name: 'VeraMono'
